### ISSUE TITLE
lunchBlockの削除

### ISSUE THREAD

**Issue by b1017173** [Hakondate/Hakondate#102]
**やること** ：SchoolモデルにおいてParentIDとLunchBlockの違いが意味的にないのに共存してるのでLunchBlockを削除する

- SchoolModelから削除
- SQLiteのSchoolテーブルから削除
- Firestoreから削除

**完成の定義**
- プログラム内からLunchBlockが削除されている

**開発について**
工数：2 時間
ブランチ：`fix/delete_lunchBlock`

**Comment by mic4dy** [comment]
よくんがえたら一つのLunchBlockに複数のParentが存在する可能性があると分かったので今の実装で問題なし。
