### ISSUE TITLE
バージョン管理手法の見直し

### ISSUE THREAD

**Issue by mic4dy** [Hakondate/Hakondate#139]
**機能名** ：いい感じにバージョン管理ができないかを検討してみる

**今の課題**
- 度重なるバージョンアップが追えていない
- 安易にバージョンアップしてビルド死ぬ（主にFirebase関連）

**参考**
- https://github.com/renovatebot/renovate

**Comment by Atori-Ikeyama** [comment]
めちゃいいですね
