### ISSUE TITLE
献立アップロード通知SlackBot

### ISSUE THREAD

**Issue by uwatcha** [Hakondate/Hakondate#223]
**概要**  

献立がアップロードされたことを通知するSlackBot

**詳細**

学校ごとに指定したGoogleDriveのフォルダにExcelファイルがアップロードされたことを通知する。
firestoreに情報が入ったことも通知する？

**完成の定義**

- 献立データをアップロードされたらSlackに通知が来る

**開発について**
工数：HOGE 4時間
ブランチ：なし

**Comment by Atori-Ikeyama** [comment]
はこんだて運用チャンネルに通知する
