### ISSUE TITLE
アプリ起動時に献立が表示されない(fix/menus_loadingにて)

### ISSUE THREAD

**Issue by uwatcha** [Hakondate/Hakondate#225]
**概要**
初回起動時に献立が読み込めないバグ

**詳細**
再現方法: アプリを起動する
1. アプリを起動する
2. 「献立は準備中です...」と表示される
3. 日付を切り替える
4. 献立が表示される
5. 起動時に選択されていた日付を開き直す
6. 献立が表示される

エラー文:
なし

**スクリーンショット**

**Flutter doctor:**

```

```

**発生機材:**
 - App Version:  [e.g. 1.0.0]

**補足事項**

- fix/menus_loadingブランチでの問題である
- daily_view_modelのupdateSelectedDay()のloadingで1秒delayしたら読み込めたが、この実装は好ましくない
- いかなる場合でもDurationを用いた実装は許されない
- 先述のloadingで読み込めるまでwhile()文を回したが、読み込みが終了しない

**Comment by Atori-Ikeyama** [comment]
https://github.com/Hakondate/Hakondate/pull/210
