### ISSUE TITLE
GASとFireStoreの連携方法の調査

### ISSUE THREAD

**Issue by tkeita1024** [Hakondate/Hakondate#80]
**やること** ：GASとFireStoreの連携方法を探し出すこと

**完成の定義**
- GASとFireStoreの連携方法が書かれているWebサイトを複数見つける
- 見つけたWebサイトからどのように実装するのかをこのissueのコメントにまとめる

**開発について**
工数：1 時間
ブランチ：なし
関連Issue：なし

**参考リンク**
[HOGE]()

**Comment by KeitaTakahashi1024** [comment]
[参考になりそうなWebサイト1](https://qiita.com/PmanRabbit/items/a76b9bc5a9d0239c9f78)
連携方法
1. GASでFirestoreと連携するためのライブラリを追加する
2. 連携するために必要なサービスアカウントの作成する
3. GASで2の作成したアカウントの認証情報とFiresotreで送信するデータの処理を行うコードを書く

**Comment by KeitaTakahashi1024** [comment]
[参考になりそうなWebサイト2](https://medium.com/@m_coder/%E3%83%90%E3%83%83%E3%82%AF%E3%82%A8%E3%83%B3%E3%83%89%E3%81%AE%E7%9F%A5%E8%AD%98%E3%81%8C%E3%81%AA%E3%81%84%E8%87%AA%E5%88%86%E3%81%8Cfirestore-googleappsscript%E3%81%A7%E7%B0%A1%E6%98%93db%E3%82%92%E6%A7%8B%E7%AF%89%E3%81%97%E3%81%9F%E8%A9%B1-def690bb3c4d)
連携方法
1. GASでFirestoreと連携するためのライブラリを追加する
2. 連携するために必要なサービスアカウントの作成する
3. GASで2の作成したアカウントの認証情報とFiresotreで送信するデータの処理を行うコードを書く
